name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-pcre:release
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
